import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { format } from 'date-fns';

export interface PDFExportOptions {
  startDate: string;
  endDate: string;
  includeCharts?: boolean;
  includeTransactions?: boolean;
  includeSummary?: boolean;
  chartSelectors?: string[];
}

export async function exportAnalyticsPDF(options: PDFExportOptions) {
  const params = new URLSearchParams({
    startDate: options.startDate,
    endDate: options.endDate,
    includeCharts: String(options.includeCharts ?? true),
    includeTransactions: String(options.includeTransactions ?? true),
    includeSummary: String(options.includeSummary ?? true),
  });

  const response = await fetch(`/api/analytics/export/pdf?${params.toString()}`);
  const result = await response.json();
  if (!result.success) {
    throw new Error(result.error?.message || 'Failed to export PDF');
  }

  const doc = new jsPDF('p', 'mm', 'a4');
  let cursorY = 20;

  const addSectionTitle = (title: string) => {
    doc.setFontSize(16);
    doc.text(title, 14, cursorY);
    cursorY += 2;
    doc.setLineWidth(0.3);
    doc.line(14, cursorY, 196, cursorY);
    cursorY += 6;
  };

  const addSummaryRow = (label: string, value: string) => {
    doc.setFontSize(12);
    doc.text(label, 16, cursorY);
    doc.text(value, 120, cursorY);
    cursorY += 6;
  };

  // Cover page
  doc.setFontSize(22);
  doc.text('Analytics Report', 14, cursorY);
  cursorY += 10;
  doc.setFontSize(12);
  doc.text(`Date Range: ${options.startDate} - ${options.endDate}`, 14, cursorY);
  cursorY += 8;
  doc.text(`Exported: ${format(new Date(), 'PPP')}`, 14, cursorY);
  cursorY += 20;

  if (options.includeSummary !== false) {
    addSectionTitle('Summary');
    addSummaryRow('Total Time Watched', result.data.summary.totalTimeWatched);
    addSummaryRow('Total Spent', result.data.summary.totalSpent);
    addSummaryRow('Content Count', String(result.data.summary.contentCount));
    cursorY += 4;
  }

  if (options.includeCharts !== false && options.chartSelectors?.length) {
    addSectionTitle('Charts');
    for (const selector of options.chartSelectors) {
      const element = document.querySelector(selector) as HTMLElement | null;
      if (!element) continue;

      const canvas = await html2canvas(element, { backgroundColor: '#ffffff', scale: 2 });
      const imgData = canvas.toDataURL('image/png');
      const imgWidth = 180;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      if (cursorY + imgHeight > 280) {
        doc.addPage();
        cursorY = 20;
      }

      doc.addImage(imgData, 'PNG', 14, cursorY, imgWidth, imgHeight);
      cursorY += imgHeight + 10;
    }
  }

  if (options.includeTransactions !== false) {
    addSectionTitle('Transactions');
    doc.setFontSize(10);
    doc.text('Date', 16, cursorY);
    doc.text('Platform', 46, cursorY);
    doc.text('Title', 76, cursorY);
    doc.text('Category', 126, cursorY);
    doc.text('Cost', 166, cursorY);
    cursorY += 6;

    result.data.transactions.slice(0, 20).forEach((tx: any) => {
      if (cursorY > 280) {
        doc.addPage();
        cursorY = 20;
      }
      doc.text(tx.date, 16, cursorY);
      doc.text(tx.platform, 46, cursorY);
      doc.text(tx.title.substring(0, 25), 76, cursorY);
      doc.text(tx.category, 126, cursorY);
      doc.text(`€${tx.cost.toFixed(2)}`, 166, cursorY);
      cursorY += 6;
    });

    if (result.data.transactions.length > 20) {
      cursorY += 4;
      doc.setFontSize(10);
      doc.text(
        `+ ${result.data.transactions.length - 20} more transactions...`,
        16,
        cursorY
      );
      cursorY += 6;
    }
  }

  doc.setFontSize(10);
  doc.text(`Generated by Pay as Play • ${format(new Date(), 'PPpp')}`, 14, 290);

  const dateSuffix = format(new Date(), 'yyyy-MM-dd');
  doc.save(`analytics-report-${dateSuffix}.pdf`);

  const history = JSON.parse(localStorage.getItem('pap-export-history') || '[]');
  history.unshift({
    id: `pdf_${Date.now()}`,
    type: 'pdf',
    dateRange: { start: options.startDate, end: options.endDate },
    createdAt: new Date().toISOString(),
  });
  localStorage.setItem('pap-export-history', JSON.stringify(history.slice(0, 10)));
}

